
    const SUCCESS = "1000"
    const FAILURE = "1001"
    const RETRY = "1002"
    const TOKEN_VEIFICATION_ERROR = "1003"
    const TOKEN_EXPIRED_ERROR = "1004"
    const JSON_WEB_TOKEN_ERROR = "1005"
  
    module.exports = {SUCCESS,FAILURE,RETRY,TOKEN_VEIFICATION_ERROR,TOKEN_EXPIRED_ERROR,JSON_WEB_TOKEN_ERROR}